/// Flutter icons DistivityIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DistivityIcons
///      fonts:
///       - asset: fonts/DistivityIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DistivityIcons {
  DistivityIcons._();

  static const _kFontFam = 'DistivityIcons';

  static const IconData carret_backward = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData carret_down = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData carret_foward = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData carret_up = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData todo = const IconData(0xe80a, fontFamily: _kFontFam);
}
